package adventure.ui;

import java.awt.Image;
import java.io.IOException;

/**
 * La classe ImageDialogUI rappresenta una finestra di dialogo modale utilizzata
 * per visualizzare un'immagine a schermo intero o in un formato grande.
 * @author simona
 */
public class ImageDialogUI extends javax.swing.JDialog {

    /**
     * Crea una nuova istanza di ImageDialogUI.
     * Questo costruttore inizializza la finestra di dialogo, imposta il titolo
     * e carica l'immagine specificata dal percorso.
     * 
     * @param parent Il {@link javax.swing.JFrame} genitore di questa finestra di dialogo.
     * @param title La {@link java.lang.String} da visualizzare come titolo della finestra di dialogo.
     * @param imagePath Il percorso della {@link java.lang.String} dell'immagine da caricare e visualizzare, relativo al classpath.
     */
    public ImageDialogUI(javax.swing.JFrame parent, String title, String imagePath) {
        super(parent, title, true); // Imposta il genitore, il titolo e la modalità
        initComponents(); // Inizializza i componenti del designer

        // Carica l'immagine
        try {
            // Controllo se la risorsa esiste
            java.net.URL imageUrl = getClass().getClassLoader().getResource(imagePath);
            if (imageUrl == null) {
                throw new IOException("Risorsa non trovata nel classpath: " + imagePath);
            }
            Image image = javax.imageio.ImageIO.read(imageUrl); 
            // Scala immagine per adattarla alla finestra
            Image scaledImage = image.getScaledInstance(580, -1, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new javax.swing.ImageIcon(scaledImage));

        } catch (IOException e) {
            imageLabel.setText("Immagine non trovata o corrotta: " + imagePath);
            imageLabel.setForeground(java.awt.Color.RED);
            System.err.println("Errore caricamento immagine: " + e.getMessage());
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(imageLabel, java.awt.BorderLayout.CENTER);

        southPanel.setLayout(new java.awt.BorderLayout());

        closeButton.setText("Chiudi");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        southPanel.add(closeButton, java.awt.BorderLayout.SOUTH);

        getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(753, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel southPanel;
    // End of variables declaration//GEN-END:variables
}
