package adventure.ui;

import java.util.List;

/**
 * La classe InventoryDialogUI rappresenta una finestra di dialogo modale utilizzata 
 * per visualizzare il contenuto dell'inventario del giocatore.
 * Popola dinamicamente la finestra con i nomi e le descrizioni degli oggetti.
 * @author simona
 */
public class InventoryDialogUI extends javax.swing.JDialog {

    /**
     * Crea una nuova istanza di InventoryDialogUI.
     * Questo costruttore inizializza la finestra di dialogo e la popola
     * con la lista degli oggetti dell'inventario fornita.
     * Ogni oggetto viene visualizzato con il suo nome e la descrizione.
     * @param parent Il {@link java.awt.JFrame} genitore di questa finestra di dialogo.
     * @param items Una {@link java.util.List} di array di {@link java.lang.String},
     * e {@code item[1] come descrizione.
     */
    public InventoryDialogUI(java.awt.Frame parent, List<String[]> items) {
        super(parent, "Inventario", true);
        initComponents();

        // Rende invisibili i modelli, questa parte è necessaria
        nameLabelTemplate.setVisible(false);
        descriptionScrollPane.setVisible(false);

        // Logica dinamica per popolare la lista
        if (items.isEmpty()) {
            javax.swing.JLabel emptyLabel = new javax.swing.JLabel("Il tuo inventario è vuoto.");
            // Stile per l'etichetta temporanea (non ha un modello)
            emptyLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 16));
            emptyLabel.setForeground(java.awt.Color.GRAY);
            emptyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            mainPanel.add(emptyLabel);
        } else {
            // Ciclo che crea gli oggetti visivi
            // Sostituisci il tuo vecchio ciclo 'for' con questo

        // Se ci sono oggetti, crea una scheda per ognuno.
        for (String[] item : items) {
            // --- NOME OGGETTO ---
            // Crea l'etichetta per il nome, usando lo stile del modello.
            javax.swing.JLabel nameLabel = new javax.swing.JLabel("• " + item[0]);
            nameLabel.setFont(nameLabelTemplate.getFont());
            nameLabel.setForeground(nameLabelTemplate.getForeground());
            nameLabel.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            mainPanel.add(nameLabel);

            // --- DESCRIZIONE OGGETTO ---
            // Crea l'area di testo per la descrizione, usando lo stile del modello.
            javax.swing.JTextArea descriptionArea = new javax.swing.JTextArea(item[1]);
            descriptionArea.setEditable(false);
            descriptionArea.setLineWrap(true);
            descriptionArea.setWrapStyleWord(true);
            descriptionArea.setFont(descriptionAreaTemplate.getFont());
            descriptionArea.setForeground(descriptionAreaTemplate.getForeground());
            descriptionArea.setBackground(new java.awt.Color(45, 45, 45));
            // FORZA L'ALLINEAMENTO A SINISTRA
            descriptionArea.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            // Riduciamo il bordo per avere meno spazio
            descriptionArea.setBorder(new javax.swing.border.EmptyBorder(2, 0, 0, 0));
            mainPanel.add(descriptionArea);

            // --- SPAZIO FISSO TRA GLI OGGETTI ---
            mainPanel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSUD = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        nameLabelTemplate = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionAreaTemplate = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario");

        jPanelSUD.setBackground(new java.awt.Color(45, 45, 45));
        jPanelSUD.setLayout(new java.awt.BorderLayout());

        closeButton.setBackground(new java.awt.Color(153, 153, 153));
        closeButton.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        closeButton.setForeground(new java.awt.Color(0, 0, 0));
        closeButton.setText("Chiudi");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanelSUD.add(closeButton, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelSUD, java.awt.BorderLayout.SOUTH);

        jScrollPane.setBackground(new java.awt.Color(45, 45, 45));
        jScrollPane.setAlignmentX(LEFT_ALIGNMENT);

        mainPanel.setBackground(new java.awt.Color(45, 45, 45));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 5, 10));
        mainPanel.setToolTipText("");
        mainPanel.setAlignmentX(LEFT_ALIGNMENT);
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

        nameLabelTemplate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nameLabelTemplate.setForeground(new java.awt.Color(255, 255, 255));
        nameLabelTemplate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabelTemplate.setLabelFor(descriptionScrollPane);
        nameLabelTemplate.setToolTipText("");
        nameLabelTemplate.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        nameLabelTemplate.setAlignmentX(LEFT_ALIGNMENT);
        nameLabelTemplate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nameLabelTemplate.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nameLabelTemplate.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        mainPanel.add(nameLabelTemplate);

        descriptionScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        descriptionScrollPane.setForeground(new java.awt.Color(255, 153, 0));
        descriptionScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        descriptionScrollPane.setToolTipText("");
        descriptionScrollPane.setAlignmentX(LEFT_ALIGNMENT);
        descriptionScrollPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        descriptionAreaTemplate.setBackground(new java.awt.Color(45, 45, 45));
        descriptionAreaTemplate.setColumns(20);
        descriptionAreaTemplate.setForeground(new java.awt.Color(255, 153, 0));
        descriptionAreaTemplate.setRows(5);
        descriptionScrollPane.setViewportView(descriptionAreaTemplate);

        mainPanel.add(descriptionScrollPane);

        jScrollPane.setViewportView(mainPanel);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(388, 484));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea descriptionAreaTemplate;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JPanel jPanelSUD;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabelTemplate;
    // End of variables declaration//GEN-END:variables
}
